name: exhalapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.4.0
  community_charts_flutter: ^1.0.1
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  path_provider: ^2.0.14
  android_path_provider: ^0.3.0
  permission_handler: ^10.2.0
  location: ^4.4.0
  bluetooth_enable_fork: ^0.1.6
  flutter_native_splash:
  fluttertoast: ^8.2.2
  http: ^0.13.6
  open_file: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#0071E4"
  color_dark: "#0071E4"
  image: "assets/images/ISO_EXHALAPP.png"

  android_12:
    icon_background_color: "#0071E4"
    icon_background_color_dark: "#0071E4"

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/ISO_EXHALAPP.png
    - assets/images/Logo-EXHALAPP_color.png
    - assets/images/Logo-EXHALAPP_blanco.png
    - assets/images/datos_totales.png
    - assets/images/duracion_total.png
    - assets/images/frec_respiratoria.png
    - assets/images/metodo_corte_c50.png
    - assets/images/metodo_corte_max.png
    - assets/images/notas.png
    - assets/images/valor_maximo.png

    - assets/icons/HOME.png
